sudo: required
services:
    - docker


before_install:
    - docker build -t paralemonade/docker_cubernetes_playground -f Dockerfile.dev .

script:
    - docker run paralemonade/docker_cubernetes_playground npm run test -- --coverage
